# Generated by Django 4.0.4 on 2022-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Country',
            field=models.CharField(default='India', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='State',
            field=models.CharField(default='India', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Sikh', 'Sikh'), ('Jain', 'Jain'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Any', 'Any'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
