# Generated by Django 4.0.4 on 2022-06-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_country_profile_state_profile_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Buddhist', 'Buddhist'), ('Any', 'Any'), ('Sikh', 'Sikh'), ('Hindu', 'Hindu'), ('Jain', 'Jain'), ('Muslim', 'Muslim'), ('Christian', 'Christian')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
