# Generated by Django 4.0.4 on 2022-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_usersocial_profile_usersocialfb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usersocialFB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usersocialINSTA',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usersocialTWT',
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('Sikh', 'Sikh'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Jain', 'Jain'), ('Muslim', 'Muslim')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
