# Generated by Django 4.0.4 on 2022-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_usersocialfb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usersocialFB',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='usersocialINSTA',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='usersocialTWT',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Any', 'Any'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Buddhist', 'Buddhist'), ('Jain', 'Jain'), ('Muslim', 'Muslim')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
