# Generated by Django 4.0.4 on 2022-06-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_usersocialfb_profile_usersocialinsta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Any', 'Any'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Sikh', 'Sikh'), ('Christian', 'Christian')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
