# Generated by Django 4.0.4 on 2022-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_wedpost_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedpost',
            name='religion',
            field=models.CharField(blank=True, choices=[('Sikh', 'Sikh'), ('Christian', 'Christian'), ('Jain', 'Jain'), ('Muslim', 'Muslim'), ('Any', 'Any'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
