# Generated by Django 4.0.4 on 2022-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_wedpost_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedpost',
            name='age',
        ),
        migrations.AlterField(
            model_name='wedpost',
            name='religion',
            field=models.CharField(blank=True, choices=[('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Sikh', 'Sikh'), ('Christian', 'Christian'), ('Any', 'Any')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
