# Generated by Django 4.0.4 on 2022-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_wedpost_age_alter_wedpost_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedpost',
            name='religion',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('Jain', 'Jain'), ('Sikh', 'Sikh'), ('Buddhist', 'Buddhist'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
