# Generated by Django 4.0.4 on 2022-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_wedpost_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedpost',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Sikh', 'Sikh'), ('Any', 'Any'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Jain', 'Jain'), ('Muslim', 'Muslim')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
