# Generated by Django 4.0.4 on 2022-06-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_wedpost_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedpost',
            name='religion',
            field=models.CharField(blank=True, choices=[('Jain', 'Jain'), ('Sikh', 'Sikh'), ('Any', 'Any'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist')], default=('Any', 'Any'), max_length=30, null=True),
        ),
    ]
